import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BookOpen,
  CheckCircle,
  Circle,
  Download,
  Eye,
  EyeOff,
  FileWarning,
  FolderSearch,
  Home,
  Library,
  ListChecks,
  LogOut,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Save,
  Search,
  Settings,
  SlidersHorizontal,
  Tags,
  Trash2,
  Users,
  X,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/** Semantic icon map — prefer these over ad-hoc lucide picks in pages. */
export const icons = {
  home: Home,
  library: Library,
  book: BookOpen,
  tags: Tags,
  admin: Settings,
  logout: LogOut,
  search: Search,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  hide: EyeOff,
  show: Eye,
  edit: Pencil,
  delete: Trash2,
  add: Plus,
  download: Download,
  play: Play,
  continue: BookOpen,
  markRead: CheckCircle,
  markUnread: Circle,
  selectAll: ListChecks,
  refresh: RefreshCw,
  back: ArrowLeft,
  forward: ArrowRight,
  close: X,
  users: Users,
  scan: FolderSearch,
  missing: FileWarning,
  readerControls: SlidersHorizontal,
  exit: X,
  save: Save,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
