services:
  mango:
    container_name: mango
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-9000}:9000"
    volumes:
      - ${MAIN_DIRECTORY_PATH:-./data}:/root/mango
      - ${CONFIG_DIRECTORY_PATH:-./config}:/root/.config/mango
